set_property SRC_FILE_INFO {cfile:{D:/uni/OneDrive - Habib University/Student shiz/DLD/DLD project/Resources/VGAtest/VGA test/VGA test.srcs/constrs_1/new/chaljapls.xdc} rfile:{../../../VGA test.srcs/constrs_1/new/chaljapls.xdc} id:1} [current_design]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J18 [get_ports {blue[3]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K18 [get_ports {blue[2]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L18 [get_ports {blue[1]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N18 [get_ports {blue[0]}]
